import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import projectsRouter from "./projects";
import tasksRouter from "./tasks";
import formulationsRouter from "./formulations";
import analyticsRouter from "./analytics";
import notificationsRouter from "./notifications";
import activityRouter from "./activity";
import searchRouter from "./search";
import departmentsRouter from "./departments";
import businessDevRouter from "./business_dev";
import projectCommentsRouter from "./project_comments";
import chatRouter from "./chat";
import aiChatRouter from "./ai_chat";
import eventsRouter from "./events";
import accountsRouter from "./accounts";
import forecastsRouter from "./forecasts";
import productionOrdersRouter from "./production_orders";
import weeklyActivitiesRouter from "./weekly_activities";
import procurementRouter from "./procurement";
import mdpRouter from "./mdp";
import accessRequestsRouter from "./access_requests";
import newsfeedRouter from "./newsfeed";
import oracleRouter from "./oracle";
import productTypesRouter from "./product_types";
import optionListsRouter from "./option_lists";
import exportRequestsRouter from "./export_requests";
import adminRouter from "./admin";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/users", usersRouter);
router.use("/projects", projectsRouter);
router.use("/projects/:projectId/comments", projectCommentsRouter);
router.use("/tasks", tasksRouter);
router.use("/formulations", formulationsRouter);
router.use("/analytics", analyticsRouter);
router.use("/notifications", notificationsRouter);
router.use("/activity", activityRouter);
router.use("/search", searchRouter);
router.use("/departments", departmentsRouter);
router.use("/business-dev", businessDevRouter);
router.use("/chat", chatRouter);
router.use("/ai-chat", aiChatRouter);
router.use("/events", eventsRouter);
router.use("/accounts", accountsRouter);
router.use("/production-orders", productionOrdersRouter);
router.use("/forecasts", forecastsRouter);
router.use("/weekly-activities", weeklyActivitiesRouter);
router.use("/procurement", procurementRouter);
router.use("/mdp", mdpRouter);
router.use("/access-requests", accessRequestsRouter);
router.use("/newsfeed", newsfeedRouter);
router.use("/oracle", oracleRouter);
router.use("/product-types", productTypesRouter);
router.use("/option-lists", optionListsRouter);
router.use("/export-requests", exportRequestsRouter);
router.use("/admin", adminRouter);

export default router;
